# Generated by Django 3.2.5 on 2021-09-03 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='cooking_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.CharField(default='sik', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('g', 'Gram'), ('num', 'Number'), ('lit', 'Liter')], default='Kg', max_length=255),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('step', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='Kafgir_API.food')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_pieces', to='Kafgir_API.food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='Kafgir_API.ingredient')),
            ],
        ),
    ]
