# Generated by Django 3.2.5 on 2021-08-31 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplan',
            name='breakfast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast', to='Kafgir_API.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner', to='Kafgir_API.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch', to='Kafgir_API.food'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('Number', 'Number'), ('Liter', 'Liter')], default='kg', max_length=255),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
