# Generated by Django 3.2.5 on 2021-09-05 15:46

import Kafgir_API.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0003_auto_20210905_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=Kafgir_API.models.user.user_directory_path),
        ),
    ]
