# Generated by Django 3.2.5 on 2021-09-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='unit',
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.CharField(default='', max_length=255),
        ),
    ]
