# Generated by Django 3.2.5 on 2021-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0005_auto_20210906_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='food',
            field=models.ManyToManyField(related_name='tags', to='Kafgir_API.Food'),
        ),
    ]
