# Generated by Django 3.2.5 on 2021-09-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0005_auto_20210906_0332'),
        ('Kafgir_API', '0006_tag_food'),
    ]

    operations = [
    ]
