# Generated by Django 3.2.5 on 2021-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cooking_time',
            field=models.CharField(max_length=32),
        ),
    ]
