# Generated by Django 3.2.5 on 2021-09-30 10:14

import Kafgir_API.models.tag
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0009_alter_food_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(null=True, upload_to=Kafgir_API.models.tag.tag_directory_path),
        ),
    ]
