# Generated by Django 3.2.5 on 2021-10-02 18:25

import Kafgir_API.models.food
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0010_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to=Kafgir_API.models.food.food_directory_path),
        ),
    ]
