# Generated by Django 3.2.5 on 2021-10-02 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Kafgir_API', '0011_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_foods',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveBigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='users',
            field=models.ManyToManyField(related_name='favorite_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
