# Generated by Django 3.2.5 on 2021-10-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0012_auto_20211002_2133'),
        ('Kafgir_API', '0013_history_category'),
    ]

    operations = [
    ]
