# Generated by Django 3.2.5 on 2021-10-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafgir_API', '0014_merge_0012_auto_20211002_2133_0013_history_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='history',
            name='lct',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='uct',
            field=models.IntegerField(null=True),
        ),
    ]
